payment_service/items/urls.py
from django.urls import path

from .views import (
    Item_Page_View,
    Success_View,
    Cancel_View,
    ItemListView,
    ItemCreateView,
    create_checkout_session
)

urlpatterns = [
    path('', ItemListView.as_view(), name='home'),
    path('create/', ItemCreateView.as_view(), name='create'),
    path('buy/<pk>/', Item_Page_View.as_view(), name='detail'),
    path('item/<pk>/', create_checkout_session, name='create_session_page'),
    path('success/', Success_View.as_view(), name='success'),
    path('cancel/', Cancel_View.as_view(), name='cancel'),
]

payment_service/payment_service/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('profiles.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('items.urls')),
    path('orders/', include('orders.urls')),
]

payment_service/orders/models.py
from django.db import models
from items.models import Item
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User


class Discount(models.Model):
    DURATION = (
        ('forever', 'forever'),
        ('once', 'once'),
    )
    percent_off = models.IntegerField()
    duration = models.CharField(choices=DURATION, max_length=9)
    duration_in_months = models.IntegerField(default=1, null=True, blank=True)

    def __str__(self):
        return f"{self.percent_off}%"


class Tax(models.Model):
    JURISDICTION = (
        ('US', 'US'),
        ('RU', 'RU')
    )

    tax_id = models.CharField(max_length=255)
    display_name = models.CharField(default='vat', max_length=10)
    jurisdiction = models.CharField(choices=JURISDICTION, max_length=2)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)
    inclusive = models.BooleanField()

    def __str__(self):
        return f"{self.jurisdiction} - {self.percentage}%"


class Order(models.Model):
    STATUS_CART = '1_cart'
    STATUS_PAID = '2_paid'
    STATUS_CHOICES = [
        (STATUS_CART, 'cart'),
        (STATUS_PAID, 'paid')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=32,
        choices=STATUS_CHOICES,
        default=STATUS_CART
        )
    amount = models.IntegerField(blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    tax = models.ForeignKey(
        Tax,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
        )
    discount = models.ManyToManyField(Discount, blank=True)
    jurisdiction = models.CharField(max_length=2, default='RU')

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} --- {self.status} --- {self.amount}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART).first()
        if not cart:
            cart = Order.objects.create(user=user, status=Order.STATUS_CART,
                                        amount=0)
        return cart

    def get_amount(self):
        amount = int(0)
        orderitems = self.orderitem_set.all()
        for item in orderitems:
            amount += item.amount
        return amount

    def get_absolute_url(self):
        return reverse("create_session_order_page", kwargs={"pk": self.pk})


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Item, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.IntegerField(null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.product} --- {self.quantity} --- {self.price}'

    @property
    def amount(self):
        return self.quantity*(self.price)


@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


class PromoCode(models.Model):
    code = models.CharField(max_length=255, unique=True)
    coupon = models.ForeignKey(Discount, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.code}"

payment_service/templates/base.html
<!doctype html>
<html lang="en">

<head>
	<title>Django Payments App</title>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
	<nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">New Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'history' %}">Order History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart_view' %}">Order</a>
                </li>
                
            </ul>
            <nav class="my-2 my-md-0 mr-md-3">
                {% if user.is_authenticated %}
                Пользователь:<strong class="p-2 text-gray-dark">{{user.username}}</strong></a>
                <li class="nav-item">
                <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
                </li>
                <li class="nav-item">
                <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
                </li>
                {% else %}
                <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
                <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
                {% endif %}
            </nav>
        </div>
    </nav>
    {% block content %}

	{% endblock content %}

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>

payment_service/templates/cancel.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron text-center mt-5">
        <h1 class="text-success">Oh, mistake!</h1>
        <h3>Mistakes...</h3>
      <img
        src="https://www.meme-arsenal.com/memes/ff77dace71d6a3141cb12bcc1891f454.jpg"
        alt="More Mistakes..."/> 
            <a href="{% url 'home' %}">home page</a>.
        </p>
    </div>
</div>
{% endblock content %}

payment_service/templates/cart.html
{% extends 'base.html' %}

{% block content %}
{% for item in items %}
    <div class="row">
        <div class="col-12 col-md-1 item">
            &nbsp;&nbsp;&nbsp;{{ forloop.counter }}
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Название единицы товара:</p>{{ item.product }}</h4>
                    <p class="card-text">Цена за единицу товара:</p>{{ item.price }} $</p>
                    <p class="card-text">Количество единиц товара:</p>{{ item.quantity }}</p>
                    <p class="card-text">Общая цена за выбранную позицию(с учетом количества):</p>{{ item.amount }} $</p>
                    <div class="col-12 col-md-1 item">
                        <form method="post" action="{% url 'cart_delete_item' item.pk %}">
                            {% csrf_token %}
                            <button type="submit" style="color: blue"><u>delete</u></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
<h5><class="card-title">Итого: {{ cart.amount }} $</h5>
<div class="card-footer d-flex">
    <button id="buy-button">Создать интент на заказ</button>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    var stripe = Stripe('{{ STRIPE_PUBLIC_KEY }}');
    let buyButton = document.getElementById('buy-button');
    buyButton.removeAttribute('disabled');
    buyButton.innerHTML = 'Создать интент на заказ';
    buyButton.addEventListener('click', function () {
        buyButton.innerHTML = 'Подождите, пожалуйста...';
        buyButton.setAttribute('disabled', '');
        fetch("{% url 'create_session_order_page' pk=cart.id %}", {method: 'GET'})
            .then(function (response) {
                return response.json()
            })
            .then(session => stripe.redirectToCheckout({sessionId: session.id}))
    });
</script>
{% if not items %}
<div class="col-12 col-md-2 item">
   <h2> NO DATA</h2>
</div>
{% endif %}
{% endblock content %}

payment_service/templates/item_create.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Create Item</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    document.querySelectorAll('input, textarea').forEach(e => {
        e.classList.add('form-control');
    })
</script>
{% endblock content %}

payment_service/templates/items_list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Product List</h1>
<div class="container">
    {% if items_list %}
    <div class="row">


        {% for i in items_list %}
        <div class="col-sm-4">
            <div class="card">
                <form method="post" action="{% url 'add_item_to_cart' pk=i.id %}">
                <div class="card-body">
                    <h4 class="card-title">{{ i.name }}</h4>
                    <p class="card-text">{{ i.description }}</p>
                </div>
                <div class="card-footer d-flex">
                    <a href="{% url 'detail' pk=i.id %}" class="btn btn-success ml-auto">Force Buy</a>
                </div>
            </p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Price: {{ i.price }} $</li>
                <li class="list-group-item">
                    {% csrf_token %}
                    <label class="form-label" for="id_quantity">Quantity:</label>
                    <input type="number" name="quantity" value="1" min="1"
                           required id="id_quantity"/>
                </li>
            </ul>
            <div class="card-body">
                <button class="learn-more-btn" type="submit">Add to Order</button>
            </div>
            </div>
        </div>
        </form>
        {% endfor %}

    </div>
    {% else %}
    <div class="alert alert-info text-center mt-5">
        The product list is empty. Please add some products first.
    </div>
    {% endif %}
</div>
{% endblock content %}

payment_service/templates/landing.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Product Detail</h1>
<div class="container">

    <div class="card">
        <div class="card-header">
            <h2>Product Detail</h2>
        </div>
        <div class="card-body">
            <div class="container row">
                <div class="col-md-10">
                    <h1>Name: {{ product.name }}</h1>
                    <p>Description: {{ product.description }}</p>
                    <p>Price: {{ product.price }} $</p>
                    <div class="form-group">
                        <label for="email">Email: </label>
                        <input type="email" name="email" id="email" class="form-control" placeholder="Email">
                        <small>Email поле для обратной связи</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex">
            <button class="btn btn-success ml-auto" id="checkout-button">Checkout</button>
        </div>
    </div>
</div>

<!-- Add JavaScript Here-->
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ STRIPE_PUBLIC_KEY }}');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function () {

        var email = document.getElementById('email').value;
        if (email.length == 0) {
            alert("Please enter your email address.");
            return;
        }

        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        fetch(href="{% url 'create_session_page' pk=product.id %}", {
            method: 'POST',
            body: JSON.stringify(
                { email: email }
            )
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>
{% endblock content %}

payment_service/templates/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <label class="form-label" for="id_username">Login</label>
    <input type="text" class="form-input" id="id_username"
                               name="username" placeholder="Login" required>
    <label class="form-label" for="id_password">Password</label>
    <input type="password" class="form-input" id="id_password"
                               name="password" placeholder="Password" required>
    <button type="submit" class="request-quote-btn">Log In</button>
</form>

{% endblock content %}

payment_service/templates/mainpage.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Product Detail</h1>
<div class="container">

    <div class="card">
        <div class="card-header">
            <h2>Product Detail</h2>
        </div>
        <div class="card-body">
            <div class="container row">
                <div class="col-md-10">
                 <h1>Страница подтверждения заказа</h1>
                  <h2>Заказ номер: {{ order.id }}</h2>
                   <p>Price:</p>{{ order.amount }}</p>
                </div>
              </div>
          </div>
      </div>
      <div class="card-footer d-flex">
          <button class="btn btn-success ml-auto" id="buy-button">Confirm order</button>
      </div>
  </div>
</div>
    {% csrf_token %}
  </body>
    <script type='text/javascript'>
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      var stripe = Stripe('{{ STRIPE_PUBLIC_KEY }}');
      var buyButton = document.getElementById('buy-button');
      buyButton.addEventListener('click', function() {
        // Create a new Checkout Session using the server-side endpoint 
        // Redirect to Stripe Session Checkout
        fetch(href="{{ order.get_absolute_url }}", {
          method: 'GET',
          headers: {
            'X-CSRFToken': csrftoken
          }
        })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });
    </script>
</html>

payment_service/templates/order_history.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Site Order History</h1>
    <div class="container">
        
        {% if object_list %}
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Customer Email</th>
                    <th>Amount</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                
                {% for i in object_list %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.user.email }}</td>
                        <td>{{ i.amount }}</td>
                        <td>
                            {% if i.status == 'STATUS_PAID' %}
                                <b class="text-success">Success</b>
                            {% else %}
                                <b class="text-danger">Failed</b>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                    
            </tbody>
        </table>
        {% else %}
        <div class="alert alert-info">
            Payment history is empty.
        </div>
        {% endif %}
            
    </div>
{% endblock content %}

payment_service/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                          {{ error|escape }}
                        </div>
                    {% endfor %}


                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}
                                    
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

payment_service/templates/success.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron text-center mt-5">
        <h1 class="text-success">Payment Success</h1>
        <p>We received your order. You can now close this window or use the
            link below to visit 
            <a href="{% url 'home' %}">home page</a>.
        </p>
    </div>
</div>
{% endblock content %}